### ISSUE TITLE
Use Eigen library to solve system of linear equations

### ISSUE THREAD

**Issue by horacelynn** [karansher/computer-graphics-ray-casting#2]
Are we allowed to include and use other functions in the Eigen library to solve system of linear equations?

**Comment by cherylchen2** [comment]
Are you referring to including the Eigen library in the `cpp` files in `src`?

**Comment by horacelynn** [comment]
Yes, in order to use functions like this: https://eigen.tuxfamily.org/dox/group__TutorialLinearAlgebra.html

**Comment by horacelynn** [comment]
Updates: Those method are too slow for it to be worth it. Just solve it the good old Cramer’s rule.
