### ISSUE TITLE
output of Sphere.cpp look different 

### ISSUE THREAD

**Issue by HELENCUICUI** [karansher/computer-graphics-ray-casting#28]
Hi! My normal.ppm looks a bit different from the picture that is given in the assignment instruction. Is this a problem? I am not sure what I did wrong to cause this. 
<img width="641" alt="Screen Shot 2022-09-25 at 7 14 51 PM" src="https://user-images.githubusercontent.com/113476839/192169967-38a19515-859d-4132-9277-20140b277f33.png">

**Comment by ValentinaManferrari** [comment]
It happened to me too but I solved it after finding very small bugs in my viewing_ray and plane intersect functions... I recommend double-checking your negative signs in those functions!

**Comment by HELENCUICUI** [comment]
Thanks a lot! I fixed it!
