### ISSUE TITLE
weird output for bunny

### ISSUE THREAD

**Issue by yixinlok** [karansher/computer-graphics-ray-casting#30]
<img width="647" alt="Screenshot 2022-09-25 at 7 58 21 PM" src="https://user-images.githubusercontent.com/81039266/192171505-4357904b-8648-4a53-bc7a-e0a012cfdf8a.png"> confused what could have possibly went wrong here because my triangle output is completely fine

**Comment by henrytwo** [comment]
Check the Quercus discussions. It looks like all your triangles are positioned at the origin, instead of being offset correctly
