### ISSUE TITLE
Wrong triangle position

### ISSUE THREAD

**Issue by shawnpl7** [karansher/computer-graphics-ray-casting#38]
My triangle appears at the bottom of this image instead of the top for some reason. All the other non-triangle images are working fine and I have been debugging this for a while. Just wondering if I'm missing something
![id (11)](https://user-images.githubusercontent.com/90327099/192584324-08d8cd70-bf5d-46a9-94f2-59aaac0a50de.jpg)

**Comment by panuelosj** [comment]
What does the triangle soup look like?

**Comment by shawnpl7** [comment]
Not sure if its an issue with my triangle soup implementation or the triangle one (since the triangle is clearly not working), or a combination of both...
![soup](https://user-images.githubusercontent.com/90327099/192619708-c71b74cd-bb40-4601-8261-fd9a0bb52262.png)

**Comment by shawnpl7** [comment]
Figured it out, error in my formula
