### ISSUE TITLE
Weird output for sphere and plane

### ISSUE THREAD

**Issue by angw135** [karansher/computer-graphics-ray-casting#40]
My output for the sphere and plane image is really strange, I would assume the problem is with my viewing ray, but I followed the formula from the slides so I'm not sure what I could be doing wrong.
![download (1)](https://user-images.githubusercontent.com/41014992/192637775-32d08d11-c3ed-453d-aa1f-aea05061b3e1.png)
edit: nvm, flipped i and j, and v needs to be multiplied by -1 since we're starting at the top left:,)

**Comment by Tahmeem** [comment]
@angw135 did you have something like u = (-1 / 2) * width + (i + 1 / 2) * (width / width pixels)  and v = 1 / 2 * height - (j + 1 / 2) * (height / height pixels) from the slides to your fix
