### ISSUE TITLE
inside-a-sphere.json Output 

### ISSUE THREAD

**Issue by HELENCUICUI** [karansher/computer-graphics-ray-casting#42]
Hi,

I got these outputs for inside-a-sphere.json. Does anyone know if these are the correct outputs? I am kinda confused about how to interpret these outputs. 
<img width="542" alt="Screen Shot 2022-09-27 at 4 53 20 PM" src="https://user-images.githubusercontent.com/113476839/192633200-4d4fb724-1406-4ae0-bf1f-c26fc5c2e3ca.png">
<img width="542" alt="Screen Shot 2022-09-27 at 4 53 32 PM" src="https://user-images.githubusercontent.com/113476839/192633232-18cabed5-c787-4594-b791-ec4d4162a84f.png">
<img width="542" alt="Screen Shot 2022-09-27 at 4 53 45 PM" src="https://user-images.githubusercontent.com/113476839/192633263-903030d1-7fbd-4dd6-8787-a93e3952eeb6.png">
Thank you in advance!

**Comment by VictorWuuuu** [comment]
i got the same output

**Comment by MicheleMassa802** [comment]
same

**Comment by HELENCUICUI** [comment]
Thanks for the reassurance!
