### ISSUE TITLE
Only three .ppm files are ever produced

### ISSUE THREAD

**Issue by madirewolf** [karansher/computer-graphics-ray-casting#45]
Whenever I compile I only get these three .ppm files

![image](https://user-images.githubusercontent.com/102978588/192819361-f5c9b002-c8dc-4d36-98f0-e314733b7f11.png)

is this normal? Where can I find the triangle-id file?

**Comment by panuelosj** [comment]
Yes, it should be id.ppm

**Comment by FarzanehCS** [comment]
For the triangle and bunny images, you need to use their own data files. In the main file, change the `read_json` function call to this for the triangle:
`read_json(argc <= 1 ? "../data/triangle.json" : argv[1], camera, objects);`

and use `"../data/bunny.json"` for the bunny.
